name: unqlite
description: Dart language bindings for unqlite databases
version: 0.0.2
homepage: https://github.com/arcticfox1919/unqlite_flutter

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  ffi: ^1.1.2
  buffer: ^1.1.1
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^4.1.2
  lints: ^1.0.0
  test: ^1.16.0

ffigen:
  llvm-path:
    - 'E:\develop\LLVM'
  output: 'lib/src/unqlite_bindings.dart'
  name: 'UnQLiteBindings'
  description: 'Holds bindings to UnQLite.'
  headers:
    entry-points:
      - '../unqlite-1.1.9/unqlite.h'
  compiler-opts:
    - '-DJX9_DISABLE_BUILTIN_FUNC -DJX9_DISABLE_DISK_IO'

  # API see:https://unqlite.org/c_api_func.html
  functions:
    include:
      # Database Engine Handle
      - unqlite_open
      - unqlite_config
      - unqlite_close

      # Key/Value (KV) Store Interfaces
      - unqlite_kv_store
      - unqlite_kv_append
      - unqlite_kv_store_fmt
      - unqlite_kv_append_fmt
      - unqlite_kv_fetch
      - unqlite_kv_fetch_callback
      - unqlite_kv_delete
      - unqlite_kv_config

      # Document (JSON) Store Interfaces powered by the Jx9 Scripting Language
      - unqlite_compile
      - unqlite_compile_file
      - unqlite_vm_config
      - unqlite_vm_exec
      - unqlite_vm_reset
      - unqlite_vm_release
      - unqlite_vm_dump
      - unqlite_vm_extract_variable

      # Cursor Iterator Interfaces
      - unqlite_kv_cursor_init
      - unqlite_kv_cursor_release
      - unqlite_kv_cursor_seek
      - unqlite_kv_cursor_first_entry
      - unqlite_kv_cursor_last_entry
      - unqlite_kv_cursor_valid_entry
      - unqlite_kv_cursor_next_entry
      - unqlite_kv_cursor_prev_entry
      - unqlite_kv_cursor_key
      - unqlite_kv_cursor_key_callback
      - unqlite_kv_cursor_data
      - unqlite_kv_cursor_data_callback
      - unqlite_kv_cursor_delete_entry
      - unqlite_kv_cursor_reset

      # Manual Transaction Manager
      - unqlite_begin
      - unqlite_commit
      - unqlite_rollback

      # Dynamically Typed Value Object Management Interfaces
      - unqlite_value_int
      - unqlite_value_int64
      - unqlite_value_bool
      - unqlite_value_null
      - unqlite_value_double
      - unqlite_value_string
      - unqlite_value_string_format
      - unqlite_value_reset_string_cursor
      - unqlite_value_resource
      - unqlite_value_release

      # Dynamically Typed Value Object Query Interfaces
      - unqlite_value_is_int
      - unqlite_value_is_float
      - unqlite_value_is_bool
      - unqlite_value_is_string
      - unqlite_value_is_null
      - unqlite_value_is_numeric
      - unqlite_value_is_callable
      - unqlite_value_is_scalar
      - unqlite_value_is_json_array
      - unqlite_value_is_json_object
      - unqlite_value_is_resource
      - unqlite_value_is_empty

      # JSON Array/Object Management Interfaces
      - unqlite_array_fetch
      - unqlite_array_walk
      - unqlite_array_add_elem
      - unqlite_array_add_strkey_elem
      - unqlite_array_count

      # Global Library Management Interfaces
      - unqlite_lib_config
      - unqlite_lib_init
      - unqlite_lib_shutdown
      - unqlite_lib_is_threadsafe
      - unqlite_lib_version
      - unqlite_lib_signature
      - unqlite_lib_ident
      - unqlite_lib_copyright